package com.example.Salon_Management_System.entity;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.LocalDate;
import java.time.LocalDateTime;

@Entity
@Table(name = "report")
@Data
@AllArgsConstructor
@NoArgsConstructor
public class Report {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long reportId;


    // ============================================================
    // REPORT TYPE
    // ============================================================

    @Column(
            nullable = false,
            length = 100
    )
    private String reportType;


    // ============================================================
    // REPORT DATE RANGE
    // ============================================================

    @Column(nullable = false)
    private LocalDate fromDate;

    @Column(nullable = false)
    private LocalDate toDate;


    // ============================================================
    // GENERATED DATE & TIME
    // ============================================================

    @Column(nullable = false)
    private LocalDateTime generatedAt;


    // ============================================================
    // GENERATED BY
    // ============================================================

    @Column(
            nullable = false,
            length = 100
    )
    private String generatedBy;


    // ============================================================
    // AUTO GENERATE DATE
    // ============================================================

    @PrePersist
    public void onCreate() {

        if (generatedAt == null) {
            generatedAt = LocalDateTime.now();
        }
    }
}